#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// Astronaut toys configuration

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_WS GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_13
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_3
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_5
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_21
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_41
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_42
// #define KEY1_BUTTON_GPIO GPIO_NUM_41
// #define KEY2_BUTTON_GPIO GPIO_NUM_42

// 触摸按钮通道定义 
#define TOUCH_CHANNEL_HEAD      (1) 
#define TOUCH_CHANNEL_NOSE      (2)  
#define TOUCH_CHANNEL_BELLY     (7) 

// #define LAMP_GPIO GPIO_NUM_18
// #define FAN_BUTTON_GPIO GPIO_NUM_46  // 风扇按键GPIO
// #define FAN_GPIO GPIO_NUM_21

// Ear Motors Control Pins for TC118S
#define EAR_MOTO_EN_GPIO    GPIO_NUM_45   // 耳朵电机电源使能引脚
#define LEFT_EAR_INA_GPIO   GPIO_NUM_15   // 左耳朵电机控制引脚A
#define LEFT_EAR_INB_GPIO   GPIO_NUM_16   // 左耳朵电机控制引脚B
#define RIGHT_EAR_INA_GPIO  GPIO_NUM_8   // 右耳朵电机控制引脚A
#define RIGHT_EAR_INB_GPIO  GPIO_NUM_9   // 右耳朵电机控制引脚B

// #define VBAT_ADC_CHANNEL         ADC_CHANNEL_10 
// #define ADC_ATTEN                ADC_ATTEN_DB_12
// #define ADC_WIDTH                ADC_BITWIDTH_DEFAULT
// #define FULL_BATTERY_VOLTAGE     4100
// #define EMPTY_BATTERY_VOLTAGE    3200

// 添加 OLED 屏幕配置
#define DISPLAY_SDA_PIN AUDIO_CODEC_I2C_SDA_PIN
#define DISPLAY_SCL_PIN AUDIO_CODEC_I2C_SCL_PIN
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

// 预留的接口
// #define 4G_TXD1_PIN  GPIO_NUM_5
// #define 4G_RXD1_PIN  GPIO_NUM_4
// #define S3_TXD0_PIN  GPIO_NUM_5
// #define S3_RXD0_PIN  GPIO_NUM_4

#define EXT_IO_35  GPIO_NUM_35
#define EXT_IO_36  GPIO_NUM_36
#define EXT_IO_37  GPIO_NUM_37
#define EXT_IO_38  GPIO_NUM_38
#define EXT_IO_39  GPIO_NUM_39

#endif // _BOARD_CONFIG_H_
