#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// Astronaut toys configuration

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_WS GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_13
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_40
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_5
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_9
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_45
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_8
#define KEY1_BUTTON_GPIO GPIO_NUM_47
#define KEY2_BUTTON_GPIO GPIO_NUM_48

// 触摸按钮通道定义 - 新增玩具触摸按键（避免与现有功能冲突）
#define TOUCH_CHANNEL_HEAD      (2) 
#define TOUCH_CHANNEL_NOSE      (1)  
#define TOUCH_CHANNEL_BELLY     (3) 

#define LAMP_GPIO GPIO_NUM_18
#define FAN_BUTTON_GPIO GPIO_NUM_46  // 风扇按键GPIO
#define FAN_GPIO GPIO_NUM_21

#define VBAT_ADC_CHANNEL         ADC_CHANNEL_9 
#define ADC_ATTEN                ADC_ATTEN_DB_12
#define ADC_WIDTH                ADC_BITWIDTH_DEFAULT
#define FULL_BATTERY_VOLTAGE     4100
#define EMPTY_BATTERY_VOLTAGE    3200

// 添加 OLED 屏幕配置
#define DISPLAY_SDA_PIN AUDIO_CODEC_I2C_SDA_PIN
#define DISPLAY_SCL_PIN AUDIO_CODEC_I2C_SCL_PIN
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

// #define BOARD_NAME "astronaut-toys-esp32s3"

// Ear Motor Control Pins for TC118S
#define LEFT_EAR_INA_GPIO   GPIO_NUM_15   // 左耳朵电机控制引脚A
#define LEFT_EAR_INB_GPIO   GPIO_NUM_16   // 左耳朵电机控制引脚B
#define RIGHT_EAR_INA_GPIO  GPIO_NUM_17   // 右耳朵电机控制引脚A
#define RIGHT_EAR_INB_GPIO  GPIO_NUM_18   // 右耳朵电机控制引脚B

#endif // _BOARD_CONFIG_H_
